---
abstract: 'HTTP(s) proxy with interface to analyze and manipulate data'
author:
  - 'Steffen Ullrich <sullr@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-HTTP_Proxy_IMP
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 6.12
  IO::Socket::SSL: 1.92
  Net::IMP: 0.6
  Net::IMP::HTTP: 0.51
  Net::Inspect: 0.29
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Queue=App-HTTP_Proxy_IMP
  homepage: https://github.com/noxxi/p5-app-http_proxy_imp
  license: http://dev.perl.org/licenses/
  repository: https://github.com/noxxi/p5-app-http_proxy_imp
version: 0.946
