--- #YAML:1.0
name:               App-HTTP_Proxy_IMP
version:            0.942
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:        6.12
    Net::IMP:        0.6
    Net::IMP::HTTP:  0.51
    Net::Inspect:    0.27
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
