---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-HTTP_Proxy_IMP
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 6.12
  Net::IMP: 0.57
  Net::IMP::HTTP: 0.2
  Net::Inspect: 0.25
version: 0.93
