--- #YAML:1.0
name:               App-HTTP_Proxy_IMP
version:            0.954
abstract:           HTTP(s) proxy with interface to analyze and manipulate data
author:
    - Steffen Ullrich <sullr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:         6.12
    IO::Socket::SSL:  1.92
    Net::IMP:         0.617
    Net::IMP::HTTP:   0.51
    Net::Inspect:     0.302
resources:
    bugtracker:  https://rt.cpan.org/Dist/Display.html?Queue=App-HTTP_Proxy_IMP
    homepage:    https://github.com/noxxi/p5-app-http_proxy_imp
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/noxxi/p5-app-http_proxy_imp
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
